# Generated by Django 5.2.12 on 2026-03-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('annual_revenue', models.FloatField()),
                ('employee_count', models.IntegerField()),
                ('compliance_score', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['industry'], name='companies_c_industr_6efa2c_idx'), models.Index(fields=['annual_revenue'], name='companies_c_annual__f6ff77_idx'), models.Index(fields=['is_active'], name='companies_c_is_acti_03043b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['total_score'], name='companies_c_total_s_07ad61_idx'), models.Index(fields=['rank'], name='companies_c_rank_07c721_idx')],
            },
        ),
    ]
